baseURL = "https://gmaurotl.com/"
languageCode = "en-us"
title = "Mauro G. Tarazona LÃ©vano"
theme = "PaperMod"

# Multilenguaje
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
disableLanguages = ["fr"] # ["es", "fr"]  # deja solo ES visible


[params]
  defaultTheme = "auto"
  author = "Mauro Gonzalo Tarazona LÃ©vano"
  description = "PhD researcher in Generative AI in wireless communications 5G/6G"
  math = true # global (tu partial usa .Params.math por pÃ¡gina)

  # PaperMod: selector de idioma
  ShowLanguageSwitcher = true
  displayFullLangName = true

    # hidePoweredBy = true
    # ShowPoweredBy = false
    # hideFooter = false

  [params.label]
    text = "Home"
    icon = ""
    iconHeight = 35

  [params.profileMode]
    enabled = true
    title = "Mauro Gonzalo Tarazona LÃ©vano"
    subtitle = "PhD Researcher | Wireless Communications & Generative AI | 5G/6G"
    imageUrl = "/avatar.jpeg"
    imageTitle = "Mauro Tarazona"
    imageWidth = 150
    imageHeight = 210

    [[params.profileMode.buttons]]
      name = "Research"
      url = "/research/"

    [[params.profileMode.buttons]]
      name = "Publications"
      url = "/publications/"

    [[params.profileMode.buttons]]
      name = "Wiki"
      url = "/wiki/"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/gmaurotl"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:mgtarlev@iteam.upv.es"

# MenÃºs por idioma (con pageRef para que apunten a la traducciÃ³n correcta)
[languages]

  [languages.en]
    languageName = "EN ðŸ‡ºðŸ‡¸"
    languageCode = "en-us"
    weight = 1

    [[languages.en.menu.main]]
      name = "About"
      pageRef = "about"
      weight = 1

    [[languages.en.menu.main]]
      name = "Research"
      pageRef = "research"
      weight = 2

    [[languages.en.menu.main]]
      name = "Publications"
      pageRef = "publications"
      weight = 3

    [[languages.en.menu.main]]
      name = "Blog"
      pageRef = "blog"
      weight = 4

    [[languages.en.menu.main]]
      name = "Wiki"
      pageRef = "wiki"
      weight = 5


  [languages.es]
    languageName = "ES ðŸ‡ªðŸ‡¸"
    languageCode = "es-es"
    weight = 2

    # Opcional: traduce label y subtÃ­tulo del perfil
    [languages.es.params.label]
      text = "Inicio"
      icon = ""
      iconHeight = 35

    [languages.es.params.profileMode]
      enabled = true
      title = "Mauro Gonzalo Tarazona LÃ©vano"
      subtitle = "Doctorando | Comunicaciones InalÃ¡mbricas & IA Generativa | 5G/6G"
      imageUrl = "/avatar.jpeg"
      imageTitle = "Mauro Tarazona"
      imageWidth = 150
      imageHeight = 210

      [[languages.es.params.profileMode.buttons]]
        name = "InvestigaciÃ³n"
        url = "/es/research/"

      [[languages.es.params.profileMode.buttons]]
        name = "Publicaciones"
        url = "/es/publications/"

      [[languages.es.params.profileMode.buttons]]
        name = "Wiki"
        url = "/es/wiki/"

    [[languages.es.menu.main]]
      name = "Sobre mÃ­"
      pageRef = "about"
      weight = 1

    [[languages.es.menu.main]]
      name = "InvestigaciÃ³n"
      pageRef = "research"
      weight = 2

    [[languages.es.menu.main]]
      name = "Publicaciones"
      pageRef = "publications"
      weight = 3

    [[languages.es.menu.main]]
      name = "Blog"
      pageRef = "blog"
      weight = 4

    [[languages.es.menu.main]]
      name = "Wiki"
      pageRef = "Wiki"
      weight = 5


  [languages.fr]
    languageName = "FR ðŸ‡«ðŸ‡·"
    languageCode = "fr-fr"
    weight = 3

    # Opcional: traduce label y subtÃ­tulo del perfil
    [languages.fr.params.label]
      text = "Accueil"
      icon = ""
      iconHeight = 35

    [languages.fr.params.profileMode]
      enabled = true
      title = "Mauro Gonzalo Tarazona LÃ©vano"
      subtitle = "Doctorant | Communications sans fil & IA gÃ©nÃ©rative | 5G/6G"
      imageUrl = "/avatar.jpeg"
      imageTitle = "Mauro Tarazona"
      imageWidth = 150
      imageHeight = 210

      [[languages.fr.params.profileMode.buttons]]
        name = "Recherche"
        url = "/fr/research/"

      [[languages.fr.params.profileMode.buttons]]
        name = "Publications"
        url = "/fr/publications/"

      [[languages.fr.params.profileMode.buttons]]
        name = "Wiki"
        url = "/fr/wiki/"

    [[languages.fr.menu.main]]
      name = "Ã€ propos"
      pageRef = "about"
      weight = 1

    [[languages.fr.menu.main]]
      name = "Recherche"
      pageRef = "research"
      weight = 2

    [[languages.fr.menu.main]]
      name = "Publications"
      pageRef = "publications"
      weight = 3

    [[languages.fr.menu.main]]
      name = "Blog"
      pageRef = "blog"
      weight = 4

    [[languages.fr.menu.main]]
      name = "Wiki"
      pageRef = "wiki"
      weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
